backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads
collections:
  - name: "footyReview" # Used in routes, e.g., /admin/collections/footyReview
    label: "Footy Review" # Used in the UI
    format: "json"
    extension: "json"
    folder: "public/posts/footyReview" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.json
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "review"}
      - {label: "PinnedPost", name: "pinned-post", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - label: 'Content Blocks'
        name: 'content-blocks'
        widget: 'list'
        types:
          - label: 'Short Text Block'
            name: 'short-text-block'
            widget: 'object'
            fields:
              - {label: "Short Text", name: "short-text", widget: "string"}
          - label: 'Long Text Block'
            name: 'long-text-block'
            widget: 'object'
            fields:
              - {label: "Long Text", name: "long-text", widget: "text"}
          - label: 'Date Time Block'
            name: 'date-time-block'
            widget: 'object'
            fields:
              - {label: "Date Time", name: "date-time", widget: "datetime", default: "", dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm", format: "LLL"}
          - label: 'Image Block'
            name: 'image-block'
            widget: 'object'
            fields:
              - {label: "Image", name: "image", widget: "image", default: '/uploads/defaults/beer-default.jpg'}

          - label: 'Score Block'
            name: 'score-block'
            widget: 'object'
            fields:
              - {label: 'value', name: 'value', widget: 'number', default: 0, valueType: "int", min: 0, max: 10, step: 1}
  - name: "beerReview" # Used in routes, e.g., /admin/collections/beerReview
    label: "Beer Review" # Used in the UI
    format: "json"
    extension: "json"
    folder: "public/posts/beerReview" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.json
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "review"}
      - {label: "PinnedPost", name: "pinned-post", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - label: 'Content Blocks'
        name: 'content-blocks'
        widget: 'list'
        types:
          - label: 'Short Text Block'
            name: 'short-text-block'
            widget: 'object'
            fields:
              - {label: "Short Text", name: "short-text", widget: "string"}
          - label: 'Long Text Block'
            name: 'long-text-block'
            widget: 'object'
            fields:
              - {label: "Long Text", name: "long-text", widget: "text"}
          - label: 'Date Time Block'
            name: 'date-time-block'
            widget: 'object'
            fields:
              - {label: "Date Time", name: "date-time", widget: "datetime", default: "", dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm", format: "LLL"}
          - label: 'Image Block'
            name: 'image-block'
            widget: 'object'
            fields:
              - {label: "Image", name: "image", widget: "image", default: '/uploads/defaults/beer-default.jpg'}

          - label: 'Score Block'
            name: 'score-block'
            widget: 'object'
            fields:
              - {label: 'value', name: 'value', widget: 'number', default: 0, valueType: "int", min: 0, max: 10, step: 1}
